"""
web_server.py
FastAPI Web Dashboard Server for CSB Quad-Core Bot.
Reads live data from `data/active_state.json` generated by the live scanner.
"""

import os
import json
import glob
import time
import logging
from fastapi import FastAPI, Request
from fastapi.staticfiles import StaticFiles
from fastapi.responses import FileResponse, HTMLResponse, JSONResponse
from datetime import datetime
from dotenv import load_dotenv

# systemd starts this with no shell environment, so os.getenv() sees nothing
# from .env unless it is loaded explicitly. Every other service in this
# project already does this; the dashboard did not, which made
# DASHBOARD_TOTP_SECRET invisible and left the Settings tab permanently
# read-only on the server no matter how often 2FA was provisioned.
# Path is explicit rather than relying on find_dotenv() walking up from
# the process CWD, which systemd's WorkingDirectory does not guarantee.
load_dotenv(os.path.join(os.path.dirname(os.path.abspath(__file__)), ".env"))

from modules import settings_manager as cfg
cfg.migrate_from_env()

app = FastAPI(
    title="CSB Quad-Core Trading Terminal",
    description="Real-time Institutional Crypto Futures Dashboard",
    version="2.0.0"
)

_ROOT = os.path.dirname(os.path.abspath(__file__))
STATIC_DIR = os.path.join(_ROOT, "static")
logging.basicConfig(level=cfg.get("LOG_LEVEL"),
                    format="%(asctime)s [%(levelname)s] %(name)s: %(message)s")
log = logging.getLogger("WebServer")

DATA_DIR = os.path.join(_ROOT, "data")
LOGS_DIR = os.path.join(_ROOT, "logs", "live")

if os.path.exists(STATIC_DIR):
    app.mount("/static", StaticFiles(directory=STATIC_DIR), name="static")

def _asset_version() -> str:
    """
    Cache-busting token derived from the newest mtime across app.js/style.css.

    Without this the browser keeps serving a cached app.js after a deploy, so
    UI changes silently do not appear (the page renders new HTML driven by old
    JS). Recomputed per request so a redeploy invalidates immediately.
    """
    newest = 0.0
    for name in ("app.js", "style.css"):
        path = os.path.join(STATIC_DIR, name)
        try:
            newest = max(newest, os.path.getmtime(path))
        except OSError:
            continue
    return str(int(newest))


@app.get("/")
async def serve_index():
    index_file = os.path.join(STATIC_DIR, "index.html")
    if os.path.exists(index_file):
        try:
            with open(index_file, "r", encoding="utf-8") as f:
                html = f.read()
            return HTMLResponse(html.replace("__ASSETV__", _asset_version()))
        except Exception:
            # Fall back to the raw file rather than 500 on a read/encoding error
            return FileResponse(index_file)
    return {"message": "CSB Web API is online."}

@app.get("/api/status")
async def get_status():
    """Returns the current state dumped by the live scanner."""
    state_file = os.path.join(DATA_DIR, "active_state.json")
    if os.path.exists(state_file):
        try:
            with open(state_file, "r") as f:
                data = json.load(f)
            return data
        except Exception:
            pass
    return {
        "timestamp": datetime.utcnow().isoformat(),
        "regime": "UNKNOWN",
        "session_pnl_pct": 0.0,
        "active_positions": [],
        "n_open": 0,
        "mode": "UNKNOWN",
    }

# Display metadata per strategy. The LIST of strategies is never hardcoded —
# it comes from StrategyFactory, so the dashboard cannot drift out of sync with
# what actually trades (the dashboard previously showed only 4 of 7).
_STRATEGY_META = {
    "CSM":        ("Cross-Sectional Momentum",  "Elite",     "24h 4-5x ATR breakout (long + short)",  "#34D399"),
    "NASOS_V4":   ("NASOS V4 Dip-Buy",         "Freqtrade", "EWO + RSI dip-buy on 5m",          "#EAB308"),
}


@app.get("/api/strategies")
async def get_strategies():
    """
    The strategies actually loaded by the engine and whether each one can
    currently take a trade.

    Four states, narrowest cause first:
      DISABLED  manually switched off via Telegram/Discord (strategy_overrides)
      OFF       permitted in NO regime — turned off by config, not by market
      IDLE      permitted somewhere, but not in the regime running right now
      ACTIVE    permitted in the current regime and able to fire
    """
    try:
        from modules.strategies.strategy_factory import StrategyFactory
        ids = [s.STRATEGY_ID for s in StrategyFactory.get_all()]
    except Exception as exc:
        return {"strategies": [], "error": f"factory unavailable: {exc}"}

    try:
        from modules.strategy_overrides import is_disabled
    except Exception:
        def is_disabled(_):
            return False

    try:
        from modules.regime_engine import REGIME_STRATEGY_PERMISSIONS as _PERMS
    except Exception:
        _PERMS = {}

    # Regime the scanner last reported. Falling back to UNKNOWN keeps a
    # permitted strategy out of ACTIVE rather than claiming it is live.
    regime = "UNKNOWN"
    state_file = os.path.join(DATA_DIR, "active_state.json")
    if os.path.exists(state_file):
        try:
            with open(state_file, "r") as f:
                regime = json.load(f).get("regime", "UNKNOWN") or "UNKNOWN"
        except Exception:
            pass

    out = []
    for sid in ids:
        name, tier, desc, colour = _STRATEGY_META.get(
            sid, (sid, "Unknown", "No description registered", "#94A3B8"))

        permitted_in = sorted(r for r, m in _PERMS.items() if m.get(sid, False))

        if is_disabled(sid):
            status = "DISABLED"
        elif not permitted_in:
            status = "OFF"
        elif regime in permitted_in:
            status = "ACTIVE"
        else:
            status = "IDLE"

        out.append({
            "id": sid, "name": name, "tier": tier, "desc": desc,
            "colour": colour,
            "status": status,
            "permitted_in": permitted_in,
        })

    return {
        "strategies": out,
        "count": len(out),
        "regime": regime,
        "active": sum(1 for s in out if s["status"] == "ACTIVE"),
    }


@app.get("/api/trades")
async def get_recent_trades():
    """Reads recent closed trades from the live JSONL logs."""
    trades = []
    # Find the most recent session JSON file
    session_files = sorted(glob.glob(os.path.join(LOGS_DIR, "session_*.json")))
    if not session_files:
        return {"trades": []}

    # Session logs are a single pretty-printed JSON object with a "trades"
    # array — not JSONL. This previously read them line-by-line and filtered on
    # record["event"] == "TRADE_EXIT", but live_logger writes "type": "EXIT",
    # so every line failed to parse and the endpoint always returned empty.
    for file in session_files[-3:]:
        try:
            with open(file, "r", encoding="utf-8") as f:
                data = json.load(f)
        except Exception:
            continue
        if isinstance(data, dict):
            trades.extend(t for t in data.get("trades", []) if isinstance(t, dict))

    # Sort by exit time descending. live_logger stamps each record as "time".
    trades.sort(key=lambda x: x.get("time", x.get("timestamp", "")), reverse=True)
    return {"trades": trades[:50]}


# ─── Performance analytics ───────────────────────────────────────────────────

def _load_all_trades() -> list:
    """Every closed trade across every session log, oldest first."""
    out = []
    for path in sorted(glob.glob(os.path.join(LOGS_DIR, "session_*.json"))):
        try:
            with open(path, "r", encoding="utf-8") as f:
                data = json.load(f)
        except Exception:
            continue
        if isinstance(data, dict):
            out.extend(t for t in data.get("trades", []) if isinstance(t, dict))
    out.sort(key=lambda t: t.get("time", ""))
    return out


def _current_period(trades: list) -> tuple:
    """
    Narrow `trades` to the equity period the wallet balance is measuring.

    The Performance tab used to sum EVERY session log on disk while the wallet
    balance tracked only trades since paper_equity.json was last reset. With
    152 logged trades against 18 in the current period, the tab showed +$8.57
    directly above a wallet of $95.75 — both correct, visibly contradictory.

    Two ways to find the boundary, in order of reliability:
      1. `period_start` written by paper_equity._blank() on reset.
      2. Fall back to the most recent N trades, N = the tracker's trade count.
         Older state files predate `period_start`; this keeps them working,
         but it drifts if a close ever failed to reach the session log.

    Returns (scoped_trades, meta).
    """
    state_file = os.path.join(DATA_DIR, "paper_equity.json")
    try:
        with open(state_file, "r", encoding="utf-8") as f:
            eq = json.load(f)
    except Exception:
        return trades, {"scope": "all", "reason": "no paper_equity.json"}

    start = eq.get("period_start")
    count = int(eq.get("trades", 0) or 0)

    if start:
        scoped = [t for t in trades if str(t.get("time", "")) >= str(start)]
        return scoped, {"scope": "period", "period_start": start,
                        "basis": "period_start"}

    if count and count < len(trades):
        # No period_start (pre-existing state file) — take the newest N.
        scoped = trades[-count:]
        return scoped, {"scope": "period", "basis": "trade_count",
                        "period_start": scoped[0].get("time") if scoped else None}

    return trades, {"scope": "all", "reason": "period covers all logged trades"}


# Below this many trades, win rate / profit factor / top-trade share are noise
# and the UI shows "—" instead of a number. See _stats().
MIN_SAMPLE_FOR_RATIOS = 5


def _stats(trades: list) -> dict:
    """
    Win rate, profit factor and expectancy for a group of trades.

    Profit factor (gross wins / gross losses) is the headline: a strategy can
    win 67% of the time and still be unprofitable if one outlier carries it,
    which is why `top_trade_share` is reported alongside — it shows how much of
    the gross profit rests on the single best trade.
    """
    n = len(trades)
    if not n:
        return {"trades": 0, "wins": 0, "win_rate": 0.0, "net": 0.0,
                "profit_factor": 0.0, "avg_win": 0.0, "avg_loss": 0.0,
                "expectancy": 0.0, "top_trade_share": 0.0, "sample_ok": False}

    nets = [float(t.get("pnl_usdt_net", 0.0)) for t in trades]
    wins = [v for v in nets if v > 0]
    losses = [v for v in nets if v <= 0]
    gross_w = sum(wins)
    gross_l = abs(sum(losses))
    net = sum(nets)

    return {
        # Ratio stats are meaningless on a handful of trades, and rendering them
        # anyway actively misleads: one losing trade in a fresh equity period
        # showed "0% win rate / PF 0.00" directly above an all-time line reading
        # +$1.00, which reads as a broken bot rather than a 1-trade sample.
        # The UI dashes them out below this threshold; counts and sums, which are
        # literal facts about the sample, are always shown.
        "sample_ok": n >= MIN_SAMPLE_FOR_RATIOS,
        "trades": n,
        "wins": len(wins),
        "win_rate": round(len(wins) / n * 100, 1),
        "net": round(net, 4),
        "profit_factor": round(gross_w / gross_l, 2) if gross_l else None,
        "avg_win": round(gross_w / len(wins), 4) if wins else 0.0,
        "avg_loss": round(-gross_l / len(losses), 4) if losses else 0.0,
        "expectancy": round(net / n, 4),
        # Share of gross profit from the single best trade — an outlier
        # dependency warning. High values mean the edge is not broad.
        "top_trade_share": round(max(wins) / gross_w * 100, 1) if wins else 0.0,
    }


@app.get("/api/performance")
async def get_performance():
    """
    Aggregate trade analytics: overall, per strategy, per symbol, per exit
    reason, plus a cumulative equity curve. Per-symbol is sorted worst-first
    so blacklist candidates surface immediately.
    """
    all_trades = _load_all_trades()
    if not all_trades:
        return {"overall": _stats([]), "by_strategy": [], "by_symbol": [],
                "by_exit": [], "equity_curve": [], "generated": None,
                "alltime": _stats([]), "period": {"scope": "all"}}

    # Scope to the current equity period so this agrees with the wallet balance.
    trades, period = _current_period(all_trades)
    period["trades_in_period"] = len(trades)
    period["trades_all_time"]  = len(all_trades)

    def group(key):
        buckets = {}
        for t in trades:
            buckets.setdefault(t.get(key, "?"), []).append(t)
        return buckets

    by_strategy = [
        {"name": k, **_stats(v)} for k, v in group("strategy").items()
    ]
    by_strategy.sort(key=lambda r: r["net"], reverse=True)

    by_symbol = [
        {"name": k, **_stats(v)} for k, v in group("symbol").items()
    ]
    by_symbol.sort(key=lambda r: r["net"])          # worst first = blacklist list

    by_exit = []
    for k, v in group("exit_reason").items():
        nets = [float(t.get("pnl_usdt_net", 0.0)) for t in v]
        by_exit.append({
            "name": k, "trades": len(v),
            "share": round(len(v) / len(trades) * 100, 1),
            "net": round(sum(nets), 4),
        })
    by_exit.sort(key=lambda r: r["trades"], reverse=True)

    equity, running = [], 0.0
    for t in trades:
        running += float(t.get("pnl_usdt_net", 0.0))
        equity.append({"time": t.get("time", ""), "equity": round(running, 4),
                       "symbol": t.get("symbol", "")})

    return {
        "overall": _stats(trades),          # current equity period
        "alltime": _stats(all_trades),      # every session log ever written
        "period": period,
        "by_strategy": by_strategy,
        "by_symbol": by_symbol,
        "by_exit": by_exit,
        "equity_curve": equity,
        "generated": datetime.utcnow().isoformat(),
    }



# ═══════════════════════════════════════════════════════════════════════════════
# Settings editor
# ═══════════════════════════════════════════════════════════════════════════════
#
# SECURITY MODEL — read this before widening anything.
#
# This dashboard has no login and is routinely published to the public internet
# through ngrok, so every endpoint is reachable by anyone holding the URL. That
# is tolerable for read-only panels; it is not tolerable for an editor that can
# change leverage or account size. Four deliberate constraints:
#
#   1. ALLOWLIST, never a blocklist. A key absent from SETTINGS_SPEC can be
#      neither read nor written, so a newly-added secret is private by default
#      rather than exposed until someone remembers to hide it.
#   2. LIVE_ENABLED is NOT editable here. Flipping paper -> real money must be a
#      deliberate act on the server, never a control on an internet-facing page.
#   3. Writes require a valid Google Authenticator (TOTP) code. With no secret
#      provisioned the API is read-only and says so — the failure mode is
#      "cannot edit", never "anyone can edit".
#   4. Failed codes are rate-limited. A 6-digit code is only ~10^6 wide and
#      pyotp accepts a +/-1 window, so an unthrottled endpoint is brute-forceable
#      in minutes. See _OTP_MAX_FAILURES.
#
# Secrets (API keys, bot tokens, webhooks, chat/guild ids) are simply absent
# from the spec, so they are never serialised to the client and never accepted.

try:
    import pyotp
except ImportError:              # editing stays disabled rather than unguarded
    pyotp = None

# Brute-force throttle for the TOTP check. Process-local: the dashboard is a
# single uvicorn process, and a restart clearing the counter is acceptable
# because it also requires server access.
_OTP_MAX_FAILURES = 5
_OTP_LOCKOUT_SECONDS = 300
_otp_failures = {"count": 0, "locked_until": 0.0}

# The editable set, its types, bounds and help text all come from
# settings_manager.SPEC — the same spec the bots validate against and the
# scanner reads from. Values live in data/settings.json and the scanner
# re-reads that file every cycle, so nearly every key applies live.
SETTINGS_SPEC = cfg.SPEC
_SPEC_BY_KEY = cfg.SPEC_BY_KEY


def _totp_configured() -> bool:
    return bool(pyotp) and bool((os.getenv("DASHBOARD_TOTP_SECRET") or "").strip())


def _check_otp(code: str) -> tuple:
    """Verify a Google Authenticator code, with lockout on repeated failure."""
    now = time.time()
    if _otp_failures["locked_until"] > now:
        wait = int(_otp_failures["locked_until"] - now)
        return False, f"Too many incorrect codes. Try again in {wait}s."
    if not _totp_configured():
        return False, ("Editing is disabled: no DASHBOARD_TOTP_SECRET is set. "
                       "Run dashboard_2fa_setup.py on the server.")
    code = (code or "").strip().replace(" ", "")
    if not code.isdigit() or len(code) != 6:
        return False, "Enter the 6-digit code from Google Authenticator."

    secret = (os.getenv("DASHBOARD_TOTP_SECRET") or "").strip()
    try:
        # valid_window=1 tolerates one 30s step of clock drift either way.
        ok = pyotp.TOTP(secret).verify(code, valid_window=1)
    except Exception as exc:
        log.error(f"settings: TOTP verify failed: {exc}")
        return False, "Two-factor verification is misconfigured on the server."

    if ok:
        _otp_failures["count"] = 0
        return True, ""

    _otp_failures["count"] += 1
    if _otp_failures["count"] >= _OTP_MAX_FAILURES:
        _otp_failures["locked_until"] = now + _OTP_LOCKOUT_SECONDS
        _otp_failures["count"] = 0
        log.warning("[SETTINGS] TOTP lockout triggered after repeated failures")
        return False, (f"Too many incorrect codes. Locked for "
                       f"{_OTP_LOCKOUT_SECONDS // 60} minutes.")
    return False, "Incorrect code."


@app.get("/api/settings")
async def get_settings():
    """Editable settings and their current values.

    Secrets are absent from SETTINGS_SPEC and therefore never reach this
    response, regardless of what is in .env.
    """
    values = cfg.get_all()
    fields = []
    for spec in SETTINGS_SPEC:
        f = dict(spec)
        f["value"] = cfg.to_str(spec["key"], values[spec["key"]])
        f["default"] = cfg.to_str(spec["key"], spec["default"])
        f["restart"] = not spec["hot"]
        fields.append(f)
    configured = _totp_configured()
    if configured:
        reason = ""
    elif not pyotp:
        reason = ("Read-only: pyotp is not installed on the server "
                  "(pip install pyotp).")
    else:
        reason = ("Read-only: two-factor is not set up. Run "
                  "dashboard_2fa_setup.py on the server, scan the code "
                  "with Google Authenticator, then restart the dashboard.")
    return {
        "fields": fields,
        "editable": configured,
        "reason": reason,
        "excluded_note": ("API keys, bot tokens, webhooks and LIVE_ENABLED are "
                          "deliberately not editable from this page."),
    }


@app.get("/api/kronos/progress")
async def get_kronos_progress():
    """How far the Kronos and whale shadow experiments are from a verdict."""
    try:
        from kronos.progress import progress
        return progress()
    except Exception as exc:
        log.error(f"kronos progress failed: {exc}")
        return JSONResponse({"error": str(exc)}, status_code=500)


@app.get("/api/settings/history")
async def get_settings_history(limit: int = 30):
    """Recent setting changes (newest first), with who made them."""
    return {"changes": cfg.history(max(1, min(200, limit)))}


@app.post("/api/settings")
async def save_settings(request: Request):
    try:
        body = await request.json()
    except Exception:
        return JSONResponse({"ok": False, "error": "invalid JSON"},
                            status_code=400)

    ok, why = _check_otp(body.get("otp", ""))
    if not ok:
        return JSONResponse({"ok": False, "error": why}, status_code=403)

    changes = body.get("changes")
    if not isinstance(changes, dict) or not changes:
        return JSONResponse({"ok": False, "error": "no changes supplied"},
                            status_code=400)

    # Never silently ignored — an unknown key means the client and the
    # server disagree about what is editable, which is worth surfacing.
    unknown = [k for k in changes if k not in _SPEC_BY_KEY]
    if unknown:
        return JSONResponse(
            {"ok": False, "error": "; ".join(f"{k}: not an editable setting"
                                             for k in unknown)},
            status_code=400)

    ok, applied, errors = cfg.update(changes, source="dashboard")
    if errors:
        status = 500 if errors == ["could not write settings.json"] else 400
        return JSONResponse({"ok": False, "error": "; ".join(errors)},
                            status_code=status)
    if not applied:
        return {"ok": True, "applied": [], "restart_required": False,
                "message": "No changes — values already match."}

    cold = [a["key"] for a in applied if not cfg.is_hot(a["key"])]
    plural = "" if len(applied) == 1 else "s"
    if cold:
        note = (f" {', '.join(cold)} take{'s' if len(cold) == 1 else ''} "
                f"effect on the next service restart; everything else is live.")
    else:
        note = " The scanner applies them on its next cycle — no restart needed."
    return {
        "ok": True,
        "applied": applied,
        "restart_required": bool(cold),
        "message": f"Saved {len(applied)} setting{plural}.{note}",
    }


SQUARE_OFF_FILE = os.path.join(DATA_DIR, "square_off_queue.json")


@app.post("/api/square_off")
async def square_off(request: Request):
    """
    Queue a position for immediate close by the live scanner.

    The web server cannot close positions directly (it has no access to the
    OrderEngine or Binance credentials). Instead it writes the request to
    data/square_off_queue.json, which the live scanner checks at the top of
    every cycle (~5s) and executes via its normal close_position path.
    """
    body = await request.json()
    symbol = body.get("symbol", "").strip().upper()
    direction = body.get("direction", "").strip().upper()

    if not symbol or direction not in ("LONG", "SHORT"):
        return JSONResponse({"ok": False, "error": "symbol and direction required"},
                            status_code=400)

    queue = []
    if os.path.exists(SQUARE_OFF_FILE):
        try:
            with open(SQUARE_OFF_FILE, "r") as f:
                queue = json.load(f)
        except Exception:
            queue = []

    already = any(r["symbol"] == symbol and r["direction"] == direction for r in queue)
    if already:
        return {"ok": True, "status": "already_queued"}

    queue.append({
        "symbol": symbol,
        "direction": direction,
        "requested_at": datetime.utcnow().isoformat(),
        "source": "web_dashboard",
    })

    os.makedirs(DATA_DIR, exist_ok=True)
    with open(SQUARE_OFF_FILE, "w") as f:
        json.dump(queue, f)

    return {"ok": True, "status": "queued"}


if __name__ == "__main__":
    import uvicorn
    # Use 0.0.0.0 so it can be accessed over network
    uvicorn.run(app, host="0.0.0.0", port=8102)



